### ISSUE TITLE
ME Vire Connector nie łączy sie z ME Glass Cable

### ISSUE THREAD

**Issue by ka21k** [StarChasers/Modpack#113]
jak w temacie nie ma połączenia pomiędzy tymi dwoma blokami. Busy sa nieaktywne.

1. ME VIRE CONNECTOR
   ID: immersiveintegration:meWireConnector

2. ME Glass Cable - Fluix
   ID: appliedenergistics2:item.ItemMultiPart

**Comment by magik6k** [comment]
Użyj transformatorów ME.
