### ISSUE TITLE
[tinker][enderio] Przepalanie magma slimy magma mud

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Modpack#123]
Po przepaleniu w alloy smelter Magma Slimy Mud otrzymuje Green Slime Crystal zamiast Magma Slime Crystal. W minecraftowym piecyku działa prawidłowo.

**Comment by alucard87pl** [comment]
When smelting Magma Slimy Mud in the Alloy smelter, the result is a Green Slime Crystal instead of the Magma Slime Crystal. The vanilla furnace does it correctly.

**Comment by marcin212** [comment]
fixed
