### ISSUE TITLE
Solary

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Modpack#128]
Dają za dużo mocy w porównaniu do silników. Będzie zmniejszona generacja.

**Comment by Acerixx** [comment]
To może zamiast nerfić podkręcić silniki?

**Comment by Spajkowiecki** [comment]
Czekaj czekaj. Ale koszt craftingu wyrównuje to co się otrzymuje w wyniku końcowym.
Bo np. ktos znajdzie inne rozwiązanie np. 10-20szt. silników na bioddisel.
a zauważ że w realnym życiu jest w pizdziec solarów które dają prąd i nie nerfią ich...

**Comment by alucard87pl** [comment]
@Spajkowiecki
Z tą różnicą, że solary w prawdziwym świecie mają wydajność rzędu 17-25% przy takich samych kosztach co silniki na paliwo płynne. Jeśli o moje zdanie chodzi, nerf solarów jest potrzebny nawet nie ze względu na ich wydajność, co na fakt zerowych kosztów utrzymania. Zauważ, że część energii z biodiesli idzie na zasilenie farm produkujących paliwo, że nie wspomnę o reszcie infrastruktury (kable, rury- tanki).

**Comment by marcin212** [comment]
zmniejszone do 4, 8, 16 RF/t
