### ISSUE TITLE
CME

### ISSUE THREAD

**Issue by magik6k** [StarChasers/Modpack#144]
https://git.starchasers.ovh/magik6k/CMEFix/src/master

**Comment by Kubuxu** [comment]
Naprawdę to dalej się dzieje?

**Comment by magik6k** [comment]
Yup..

**Comment by Matrix89** [comment]
@Kubuxu uczyć się!

**Comment by marcin212** [comment]
@Kubuxu widzę, że labki z git-a.

**Comment by Kubuxu** [comment]
Heh, labki z formatowania dysków. Pouczę się w domu.
