### ISSUE TITLE
CPU(tier 3) z OC jest uncraftable

### ISSUE THREAD

**Issue by Matrix89** [StarChasers/Modpack#148]
Diament w craftingu daje Diamond Nugget a oc wymaga Diamond Chip

**Comment by marcin212** [comment]
@Matrix89 daj dokładną nazwę to zmienię w configu OC, żeby korzystało z tego co powstaje.

**Comment by Matrix89** [comment]
@marcin212 extrabitmanipulation:DiamondNugget
