### ISSUE TITLE
Mody do dodania

### ISSUE THREAD

**Issue by alucard87pl** [StarChasers/Modpack#151]
- [x] [Light Level Overlay](https://mods.curse.com/mc-mods/minecraft/226670-light-level-overlay-reloaded#t1:description)
- [ ] [Ender Storage](https://mods.curse.com/mc-mods/minecraft/245174-ender-storage-1-8)

Do przemyślenia:
- [x] [ArchitectureCraft](https://mods.curse.com/mc-mods/minecraft/242001-architecturecraft#t1:other-downloads)
- [x] [Platforms!](https://mods.curse.com/mc-mods/minecraft/244786-platforms)
- [ ] [FFS (For Fuck's Sake...)](https://mods.curse.com/mc-mods/minecraft/232683-ffs-fancy-fluid-storage#t1:other-downloads)

**Comment by marcin212** [comment]
Zamieniłem enderstorage na:
- [ ] [EnderTanks](https://minecraft.curseforge.com/projects/endertanks)
- [ ] [MultiStorage](https://minecraft.curseforge.com/projects/multistorage)

ponieważ ender storage wymaga liba i cora, a platformy wymagają innego cora, który jest wymagany przez zamienniki.

**Comment by marcin212** [comment]
dodane
