### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Kuboczoch** [StarChasers/Modpack#152]
Crash nastapil po podniesieniu robaczka z ziemi i spojrzenie na niego w eq
https://hastebin.com/ibovoricam.sql

**Comment by marcin212** [comment]
a robaczki z jakiego moda?

**Comment by Kuboczoch** [comment]
@marcin212 podobno Actually Additions, takie robaczki, które wyskakują z ziemi kiedy zaczniesz je orać
