### ISSUE TITLE
[Mekanizm] otwieranie maszyn kablem lub rura kladzie ja i nie otwiera maszyny

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Modpack#171]

**Comment by marcin212** [comment]
Patrzyłem w kod kabli. Problem jest z maszyną, którą próbujesz otworzyć. Zwraca złą wartość z metody jak otwiera GUI. Podaj maszynę albo listę maszyn. Jak tak dzieje się z piecykiem z MC to będzie wina kabli, ale to bardzo dziwne jest wtedy i bardziej skomplikowane. Czekam na listę maszyn.

**Comment by cola98765** [comment]
wszystko co ma gui i nie jest zablokowany klocek (afaik)

**Comment by marcin212** [comment]
@cola98765 Możesz sprawdzić czy dale to jest?

**Comment by marcin212** [comment]
fixed
