### ISSUE TITLE
[Mekanism] Crash przy układaniu receptury na Elite Fluid Tank w RS.

### ISSUE THREAD

**Issue by alucard87pl** [StarChasers/Modpack#173]
https://pastebin.com/K1zJLXdU

**Comment by alucard87pl** [comment]
Chyba przez to, że tank przy upgradowaniu nie może mieć w sobie płynu.

**Comment by marcin212** [comment]
Paste wygasł. Jak się jeszcze raz wywali daj znać w nowym issue.
