### ISSUE TITLE
[Forestry] Scented Paneling crafting

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Modpack#176]
Crafting Scented Paneling zużywa od 1 do 4 Royal Jelly.

**Comment by Acerixx** [comment]
Prawdopodobnie któryś mod coś override'uje

**Comment by Acerixx** [comment]
https://www.youtube.com/watch?v=cF-hfVccAkM

**Comment by marcin212** [comment]
jak będzie znikać na 1.12.1 to napisz
