### ISSUE TITLE
[IE][Propozycja] Wyższe poziomy przewodów

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Modpack#181]
Przy przesyłaniu większej ilości energii niewygodne jest korzystanie przewodów. 
T4 
- I/O: 16k
- Transfer: 128k
T5
- I/O: 64k
- Transfer: 512k

**Comment by marcin212** [comment]
robisz słup i robisz kilka kabli

**Comment by marcin212** [comment]
done
