### ISSUE TITLE
mekanizm - kable przestają działać co jakiś czas

### ISSUE THREAD

**Issue by serekk11** [StarChasers/Modpack#187]
wszelkie przewody z tego moda potrafią sie zbugować i przestać działać trzeba je zniszczyć i postawić na nowo, prawdopodobnie problem przy chunk update

**Comment by marcin212** [comment]
Nowy minecraft. Nowa wersja mekanismu. Jest spora szansa, że zostało naprawione. Jak nie to proszę o nowe issue.
