### ISSUE TITLE
Genetyka

### ISSUE THREAD

**Issue by Axoji** [StarChasers/Modpack#190]
Crash po otworzeniu Genepoola. Możliwe do reprodukcji, nawet kilkukrotnie zostało przetestowane – testowy egzemplarz 
[fml-client-latest.log.txt](https://github.com/StarChasers/Modpack/files/1272520/fml-client-latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/StarChasers/Modpack/files/1272522/fml-junk-earlystartup.log.txt)
[latest.log.txt](https://github.com/StarChasers/Modpack/files/1272521/latest.log.txt)

stoi obok punku teleportacji "axoi's bees".

**Comment by marcin212** [comment]
fixed
