### ISSUE TITLE
Recepta Basic Crushing Factory

### ISSUE THREAD

**Issue by Wieku** [StarChasers/Modpack#198]
Chcąc wytworzyć Basic Crushing Factory otrzymałem Basic Smelting Factory

**Comment by Wieku** [comment]
Z niewiadomych przyczyn przy drugiej próbie stworzył się Basic Crushing Factory.

**Comment by marcin212** [comment]
hmm, dziwne. Nie pomyliłeś recept? Ikonki są podobne. My już kilka robiliśmy i problemu nie było. Jak coś to proszę o otworzenie jeszcze raz issue.
