### ISSUE TITLE
[Forestry] Trading Station - Wymaga usprawnienia

### ISSUE THREAD

**Issue by ka21k** [StarChasers/Modpack#31]
Ore Dictionary i Ghost Items dla slotów od handlu
Wyciąganie i wkładanie itemów z różnych stron

**Comment by marcin212** [comment]
@alucard87pl 
Kilka propozycji usprawnień TradeStation:
- itemy widmo albo wyszukiwarka(teraz trzeba mieć dany item który się chce kupować w odpowiedniej ilości)(przykład wyszukiwarki http://i.ytimg.com/vi/milg8tDclI8/maxresdefault.jpg)
-możliwość wyciągania itemów otrzymanych za handel
-obsługa oredictionary, tych samych NBT-tagów (podobne do tego :http://teamcofh.com/wp-content/uploads/2014/07/GuiItemduct-300x187.png )

**Comment by alucard87pl** [comment]
@marcin212 

A few conveniences in the Trade Station and Catalog
- Ghost items or a search functionality (now you have to have the item you want to buy in the quantity you want to buy) Something like http://i.ytimg.com/vi/milg8tDclI8/maxresdefault.jpg
- ability to pull the received items out (pipes, hoppers, import busses, etc.)
- Ore Dictionary, NBT tags support, like http://teamcofh.com/wp-content/uploads/2014/07/GuiItemduct-300x187.png
- Search functionality in the Catalog
