### ISSUE TITLE
[Forestry] Wyświetlanie informacji o ilości listów zasłania.

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Modpack#35]
@alucard87pl 
Topic: Wyświetlanie informacji o ilości listów.
Message:
Mógłbym prosić o dodanie opcji w configu na zmianę pozycji( lewy dolny, prawy górny itp.) wyświetlania informacji o ilości nie przeczytanych listów, wiadomość?

**Comment by alucard87pl** [comment]
@marcin212 
Topic: Received letters information
Message:
Would it be possible to add a config option for choosing where to display the received letters information (in which corner of the screen, for example).
