### ISSUE TITLE
[NEW][RC][feature request]kolorowy dym ze smokerow

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Modpack#65]
gdy sie kliknie prawym na smoker z railcrafta z barwnikiem w rece powinno sie dac zmienic kolor dymu.

**Comment by alucard87pl** [comment]
Colourizable smokers

How about adding an option to the smmokers that would enable changing the smoke color? Like, right-clicking with a dye, or having a dye somewhere in the crafting recipe? Not all smoke is black :)
