### ISSUE TITLE
Synchronizacja GUI Farm z Forestry

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Modpack#86]
GUI farm nie synchronizuje się poprawnie na SMP. Wkładasz płytkę żeby zniemić typ farmy po czym druga osoba otwiera GUI i nie widzi jej. Wyjście i wejście na serwer naprawia problem.

forestry_1.7.10-4.2.5.52

**Comment by alucard87pl** [comment]
The farm GUI doesn't sync properly on SMP. When a Circuit board is put into its slot by a player, other players don't see it put in until they log out and back in.

forestry_1.7.10-4.2.5.52

**Comment by marcin212** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1040
