### ISSUE TITLE
Rotten food zaburza gre

### ISSUE THREAD

**Issue by Pucoslaw** [StarChasers/Modpack#90]
Nalezy wyłaczyć funkcje rotten food która powoduje ze klikniecie prawym na rosline powodujej jej wzrost (identycznie jak bonemeal). 
Toz aburza gre ponieważ całkowicie niweluje czas wrostu roslin wystarczy "zgnic" 16 jedzenia i juz mozna miec na zawołanie wzrost nawet najtrudniejszych w hodowli roslin.

**Comment by Kubuxu** [comment]
Twoja matma coś nie działą.
Zgnite jedzienie pochodzi z jedzenia. To poprostu zamyka ciąg, jedzenie które nie zosało zużyte może być wykoszystane ponownie do wychodowania nowego ze stratą 3-4x.

TLDR: Gnicie jedzenia się nie opłaca, a jak to wyłączysz 1. zgnite jedzenie nie będzie miało totalnie użytki i będzie poprostu wkurzające 2. nie będzie żadnego odpowiednika bone meal w grze.

**Comment by marcin212** [comment]
Kubuxu nie zgodze się z tobą. Zgnite jedzenie powstaje np. z jabłek któreych mamy na stack-i. W skrzynkach aktualnie jest 20-30 stack-ów zgniłego jedzenia.

**Comment by marcin212** [comment]
fixed
