### ISSUE TITLE
Więcej metod otrzymania białego barwnika aka. bonemeala

### ISSUE THREAD

**Issue by LudziE12** [StarChasers/Modpack#91]
Brakuje innych metod otrzymania białego barwnika oprócz mielenia kości - obecnie do zdobycia tylko z wody. Potrzebne są do dróg.

**Comment by alucard87pl** [comment]
a z białych vanillowych kwiatków się nie da?

**Comment by Kubuxu** [comment]
Nie da się, daje jasno szary a poza tym  żeby wychodować białe kwatki potrzebujesz bonemeala...
Inaczej się szybko skończą.

(Kwatki rosną zawsze w tym samym miejscu FIFY).

**Comment by marcin212** [comment]
Coś wymyślę. Może jakieś propozycję na crafting WhiteDye. Dlaczego na dye, bo nie działa jak mączka.

**Comment by Axoji** [comment]
Może te białe jagody, skoro czarny craftujemy z czarnych? candleberries.

**Comment by marcin212** [comment]
Jak nie ma innych propozycji to wykorzystam białe jagody.
