### ISSUE TITLE
Produkcja Dustu/gliny

### ISSUE THREAD

**Issue by Axoji** [StarChasers/Modpack#94]
Chciałabym poprosić o dodanie jakiejś recepty maszynowej na dust - na przykład do rock crushera z piasku z 50% szans - tak aby nie zaburzyło to balansu i umożliwiło automatyczną produkcję gliny z niego, która jest jednym z najbardziej potrzebnych i najrzadszych materiałów budowlanych na serwerze.

Ewentualnie chciałabym poprosić o inną receptę na glinę - możliwą do automatyzacji.

**Comment by marcin212** [comment]
Można pomysleć ale roboty z OC potrafią uzywać itemów. @Axoji

**Comment by marcin212** [comment]
Dodałem recpetę do Crushera. Z piasku robi proszek
