### ISSUE TITLE
nowe recepty do zarowek energooszczednych.

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Modpack#96]
fajnie by bylo gdyby 8W zarowki craftowalo sie z copper electron tubow a 15W z gold electron tubow i bez miedzi na dole.

**Comment by marcin212** [comment]
Dobry pomysł. Jak zrobisz recepte do minetweaker-a to dodam.

**Comment by cola98765** [comment]
recipes.addShaped(<zettaindustries:LightBulb.2>*8, [
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],       
[<Forestry:thermionicTubes:0>, null, <Forestry:thermionicTubes:0>],
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);

recipes.addShaped(<zettaindustries:LightBulb.3>*8, [
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],       
[<Forestry:thermionicTubes:4>, null, <Forestry:thermionicTubes:4>],
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);

**Comment by cola98765** [comment]
```
recipes.addShaped(<zettaindustries:LightBulb.2>*8, [
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],       
[<Forestry:thermionicTubes:0>, null, <Forestry:thermionicTubes:0>],
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);

recipes.addShaped(<zettaindustries:LightBulb.3>*8, [
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],       
[<Forestry:thermionicTubes:4>, null, <Forestry:thermionicTubes:4>],
[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);

**Comment by marcin212** [comment]
done
