### ISSUE TITLE
Brak receptur z białym barwnikiem

### ISSUE THREAD

**Issue by LudziE12** [StarChasers/Modpack#99]
Jak w tytule, niektóre recepty, które możnaby zastąpić białym barwnikiem zamiast mączki nadal jej potrzebują. Przy budowie dróg chcemy wykorzystać Asphault z pasami z Simply Paths, ale do craftingu potrzebna jest mączka kostna.

**Comment by marcin212** [comment]
Poproszę o id(tekstowe np. zettaindustries:cable:1) bloków które nie działaja prawidłowo

**Comment by marcin212** [comment]
Jest sporo mączki jak przesiewasz dust. Przetestowane
